### ISSUE TITLE
This seems like a better place for…

### ISSUE THREAD

**Issue by hrbrmstr** [ultinomics/xmlExtras#2]
https://github.com/hrbrmstr/htmltidy/blob/master/R/xmlview.R (and its counterparts).

Let me know if you'd like a PR into here (and removal from that pkg).

**Comment by dantonnoriega** [comment]
Considering that
1. This was something I played around with long ago and doesn’t work all the time.
2. I’ve not thought about in like years
3. That bob effing rudis has a similar (and very likely, working, package)

I’m happy to merge this into something else. Not sure what you mean by “removal from that package”. Is xmltools being used somewhere? (I hope not, it’s performance is dubious.)

**Comment by hrbrmstr** [comment]
it's getting _alot_ of attention this week :-)

**Comment by dantonnoriega** [comment]
Hopefully about how one shouldn’t use it haha
