### ISSUE TITLE
need to export pipe operator

### ISSUE THREAD

**Issue by lecy** [ultinomics/xmlExtras#5]
I get the following error when running this function: 

```r
xmltools::xml_get_paths( x, only_terminal_parent = TRUE )

# > ( xmltools::xml_get_paths( x, only_terminal_parent = TRUE ))
# Error in path_dig(nodeset, mark_terminal = mark_terminal) %>% lapply(. %>%  : 
#   could not find function "%>%"
```

The error goes away if I load the dplyr or magrittr library, but I created a pull request to add a utils.R file to import the pipe operator for internal functions in your package. 

I am referencing `xmltools::xml_get_paths` inside of functions in another package, so I can't assume the user will know to load dplyr or magrittr beforehand.

**Comment by dantonnoriega** [comment]
Resolved with #6
