### ISSUE TITLE
as_tibble() deprecated arguments

### ISSUE THREAD

**Issue by lecy** [ultinomics/xmlExtras#7]
Code currently produces the following warning: 

```r
Warning message:
The `x` argument of `as_tibble.matrix()` must have unique column names if
`.name_repair` is omitted as of tibble 2.0.0.
i Using compatibility `.name_repair`.
i The deprecated feature was likely used in the xmltools package.
  Please report the issue to the authors.
```

From xml_dig_df() lines 25-58 : 

```r
          DF <- nodeset[terminal] %>%
            xml2::xml_text() %>%
            t() %>%
            tibble::as_tibble()
```

And lines 43-46: 

```r
        DF <- nodeset[terminal] %>%
          xml2::xml_text() %>%
          t() %>%
          tibble::as_tibble()
```

I think the best fix is to add the argument: 

```r
nodeset[terminal] %>%
          xml2::xml_text() %>%
          t() %>%
          tibble::as_tibble( .name_repair = "unique" )
```

**.name_repair** argument: Treatment of problematic column names:

* "minimal": No name repair or checks, beyond basic existence,
* "unique": Make sure names are unique and not empty,
* "check_unique": (default value), no name repair, but check they are unique,
* "universal": Make the names unique and syntactic

**Comment by dantonnoriega** [comment]
closed in #8
